[package]
name = "vx-cv"
version = "0.1.0"
authors = ["Ueki Masaru <masaru.ueki@itage.co.jp>"]

[dependencies]
vx = { path = "../vx" }
vx-api = { path = "../vx-api" }
cv = { git = "https://github.com/nebgnahz/cv-rs.git" }
